package-lock.json, script/seed.js, server/api/index.js, server/api/questions.js, server/db/models/AQuestion.js, server/db/models/CTStuff.js, server/db/models/EQuestion.js, server/db/models/RQuestion.js, server/db/models/index.js, server/db/models/mainTopic.js, server/db/models/questionList.js, server/db/models/questions.js, server/db/models/subTopic.js
Seed now fully creates questions and eager loads everything for one topic. Routes now has an api route /api/questions in order to fetch questions.
Should add in tests, and find a way to possibly make seed definitions of questions more cleaner.
=> Server models

client/components/index.js, client/components/navbar.js, client/components/problem.js, client/components/subtopic.js, client/components/topic.js, client/routes.js, package-lock.json, package.json
=> Adding comp

client/components/editor.js
=> ide is working. checking the code using the input and outputon state

client/components/smartQuestion.js, server/api/questions.js
=> New api route

client/components/editor.js
Now the IDE raises errors message. Also, it cleans the errors message after the user starts typing again.
=> Catching errors on ide

client/components/approach.js, client/components/editor.js, client/components/example.js, client/components/optimize.js, client/components/profile.js, client/components/repeat.js, client/routes.js
=> progress bar, spacing, redirect, profile page

client/components/navbar.js, server/api/newQuestion.js
Small change to allow access to submit via navbar
=> Added a way to access the submit form

client/components/editor.js, package-lock.json, server/api/users.js, server/db/models/userQuestions.js
Saves the code, but I couldn't figure out the regex to have the code put a message.
=> Code saves, does not display message

client/components/screenShare.js, client/components/testVideoComponent.js, screen-capture/extension/extension.js, screen-capture/extension/manifest.json
=> videoConf plus screenShare

client/components/screenShare.js, public/index.html
=> made the chrome ext Id available

client/components/profile.js, server/api/users.spec.js
=> test update

client/components/approachNoHelp.js, client/components/exampleNoHelp.js, client/components/repeatNoHelp.js, client/components/subtopic.js
- now progress is tracked on no help route
=> fixes progress on no help

client/components/navbar.js, client/components/testVideoComponent.js, public/style.css
=> formatted video

client/components/questionForm.js, client/components/testVideoComponent.js, public/style.css
=> Question form

client/components/editor.js, package-lock.json
=> color and position in the editor for errors

client/components/editor.js, client/components/profile.js, client/components/questionForm.js
=> editor colors

client/components/optimize.js, package-lock.json, package.json, script/seed.js, server/db/models/AQuestion.js
Remember that for each graph needs new stuff added into it's seed to display properly.
=> Graph working, displays code as text but needs to be formatted. Also entry form needs to be updated.

server/db/models/AQuestion.js
=> Slight fixes, default values

client/components/editor.spec.js, package-lock.json
=> fixing travis and editor test to avoid weird error

client/components/optimize.js, client/components/optimizeNoHelp.js, package-lock.json, script/seed.js, server/db/models/questions.js
Basically just makes use of two new properties of the questions (not questionlist) model.
And yes, our DB is getting messy, and I do wish that "just add another table/column" wasn't a solution for every problem I happened to face.
=> Unguided optimize

client/components/editor.js, client/components/screenShare.js, client/components/testVideoComponent.js, public/style.css
=> Video fullscreen
